# Generated by Django 4.2.18 on 2025-02-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About_Us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="aboutus_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Awards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=500)),
                ("year_awarded", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="award_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Core_Values",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="values_images/")),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField()),
            ],
        ),
    ]
