# Generated by Django 4.2.18 on 2025-02-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default="Untitled Review", max_length=100),
        ),
    ]
