# Generated by Django 4.2.18 on 2025-02-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=4)),
                ("description", models.TextField(max_length=1000)),
                (
                    "spiciness_level",
                    models.IntegerField(
                        choices=[
                            (0, "Not Spicy 🌿"),
                            (1, "Mild 🌶️"),
                            (2, "Medium 🌶️🌶️"),
                            (3, "Hot 🌶️🌶️🌶️"),
                        ],
                        default=0,
                    ),
                ),
                ("vegan", models.BooleanField(default=False)),
                ("gluten_free", models.BooleanField(default=False)),
                ("allergens", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="menu_images/")),
            ],
        ),
    ]
