# Generated by Django 4.2.18 on 2025-02-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_category_menu_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="image",
            field=models.ImageField(upload_to="static/images/menu_images"),
        ),
    ]
