# Generated by Django 4.2.18 on 2025-02-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_menu_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="image",
            field=models.ImageField(upload_to="menu_images/"),
        ),
    ]
